name: Github Action

on:
  pull_request:
  push:
    branches: [main]

jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
